<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXhwTKLa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXhwTKLa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXhwTKLa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXhwTKLa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXhwTKLa\App_KernelDevDebugContainer([
    'container.build_hash' => 'XhwTKLa',
    'container.build_id' => '9c5af152',
    'container.build_time' => 1621033990,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXhwTKLa');
