<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTsyQdtX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTsyQdtX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTsyQdtX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTsyQdtX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTsyQdtX\App_KernelDevDebugContainer([
    'container.build_hash' => 'TsyQdtX',
    'container.build_id' => 'a6d5741b',
    'container.build_time' => 1621173155,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTsyQdtX');
